### ISSUE TITLE
lina -c creates and executeable file 32bit elf, etc.but segfaults (solved)

### ISSUE THREAD

**Issue by ghost** [albertvanderhorst/lina#1]
lina -c works by generating, but even the hellow.frt that comes with it segfaults when you type hellow and enter:
larry@zion-3:~/lina$ lina -c hellow.frt
larry@zion-3:~/lina$ ./hellow
Segmentation fault
larry@zion-3:~/lina$ 

btw, lina -e works but i couldn't load 3 for the TURNKEY to work either.

**Comment by albertvanderhorst** [comment]
The library file was not properly configured. If you use this installation, you have to run **lina** with **forth.lab** in the working directory. I'm surprised that any options worked. The only explanation for your experience is that you had a **/usr/lib/forth.lab** remaining from an old installation, and that doesn't match.

I have  fixed  **ci86.gnr** and added a **lina** so that you need not make anything.

P.S. **TURNKEY** works after "WANT TURNKEY" , not by loading screen 3.
